### ISSUE TITLE
업비트 REST API 요청시 캔들데이터 시간 불일치

### ISSUE THREAD

**Issue by Codejune** [showmethecoin/upbit-trader#3]
``candle_df = await pyupbit.get_ohlcv(ticker=code,
                                                        interval="minute1",
                                                        count=200)``

- server.py에서 위의 함수를 통한 캔들데이터 요청시 일부 요청에 대해서 캔들 데이터의 마지막 데이터가 2~3분 정도 누락되는 경우를 확인
- 이에따라 대기열 큐형식의 프로그램 설계 구조 변경 후 문제가 지속될 시 핸들링이 필요함
- @Codejune @kimjeus

**Comment by frics** [comment]
이건 아니죠!!!
