### ISSUE TITLE
이 프로그램이 지금 정상 구동 되는건가요? 된다면 pythonanywhere 에서 실행 순서 알 수 있을까요?

### ISSUE THREAD

**Issue by presio2** [showmethecoin/upbit-trader#4]
git clone https://github.com/showmethecoin/upbit-trader.git
cd upbit-trader
vim config.yaml.example -> 엑세스, 시크릿 키 입력
여기서 부터 잘 모르겠네요. 코딩 경험이 없습니다.
pip3 install virtualenv
virtualenv upbit --python=python3.8
source upbit/bin/activate
pip install -r requirements.txt
cd src
python main.py
이렇게 하면 되나요?

**Comment by Codejune** [comment]
아직 개발중인 단계라서 현재는 정상적인 구동이 불가능합니다 😅 
지속적인 업데이트 및 문서 작성 예정이니 참고 바랍니다!

**Comment by presio2** [comment]
넵 감사합니다
