### ISSUE TITLE
GUI 남은 사항

### ISSUE THREAD

**Issue by ChanYangYu** [showmethecoin/upbit-trader#5]
- [x] login 및 메인화면 프로젝트 연결
- [ ] trade 로직구현
- [ ] 사용자 홀딩 리스트 구현
- [ ] MainWindow SecondPage UI 구현

**Comment by Codejune** [comment]
이건 앞으로 예정사항이니까 레포지토리에서 Projects 탭에서 추가해주세용

**Comment by Codejune** [comment]
이건 발견된 문제가 아니라 예정사항이니까 Projects 탭에서 메모로 추가해줘
